version: '3.7'

services:
  zen-app:
    container_name: zen-app
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - zen-postgres
  zen-postgres:
    container_name: zen-postgres
    image: postgres:16
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - zen-pgdata:/var/lib/postgresql/data
networks:
  webnet:
volumes:
  zen-pgdata:
